spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/${POSTGRES_DB:ong-pet}}
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:ongpet}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASS:ongpet123}}
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:${RABBITMQ_USER:ongpet}}
    password: ${SPRING_RABBITMQ_PASSWORD:${RABBITMQ_PASS:ongpet123}}

  jpa:
    show-sql: true

s3:
  endpoint: ${S3_ENDPOINT:http://localhost:9000}
  region: us-east-1
  access-key: ${S3_ACCESS_KEY:${MINIO_ROOT_USER:ongpetadmin}}
  secret-key: ${S3_SECRET_KEY:${MINIO_ROOT_PASSWORD:ongpet123}}
  bucket-name: ${S3_BUCKET_NAME:${MINIO_BUCKET_NAME:ong-pet-midias}}